#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Fri Jan 31 15:18:14 2020

@author: vozdecky
"""

import cv2
from matplotlib import pyplot as plt
import numpy as np
import csv

results = []
with open("CSV_with_0.92_emmy.csv") as csvfile:
    reader = csv.reader(csvfile, quoting=csv.QUOTE_NONNUMERIC) # change contents to floats
    for row in reader: # each row is a list
        results.append(row)


image = np.array(results)

test = np.ones((600,400))*255
cv2.line(image,(0,0),(100,100),(30,30,30),thickness=10)

plt.imshow(image)
plt.show()